src/androidTest/kotlin/com/criptext/mail/mocks/MockJSONData.kt
src/androidTest/kotlin/com/criptext/mail/scenes/composer/data/LoadInitialDataWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/composer/data/SaveEmailWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/composer/data/SearchEmailWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/composer/data/UploadAttachmentWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/emaildetail/data/DownloadAttachmentWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/emaildetail/data/ReadEmailsWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/mailbox/data/MoveEmailThreadsWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/mailbox/data/SendEmailWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/mailbox/data/UpdateMailboxWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/mailbox/data/UserDataWriterTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/mailbox/feed/data/GetEmailPreviewWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/settings/data/CreateCustomLabelWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/signal/EncryptFileByChunksTest.kt
src/androidTest/kotlin/com/criptext/mail/websocket/data/UpdateDeliveryStatusWorkerTest.kt
src/main/kotlin/com/criptext/mail/utils/EventHelper.kt
src/main/kotlin/com/criptext/mail/websocket/data/UpdateDeliveryStatusWorker.kt

Also created a new test for the ReadEmailsWorker and fixed two classes that were not behaving correctly and were failing the tests because of that.

Fixed all android tests.

---

build.gradle
src/main/kotlin/com/criptext/mail/scenes/mailbox/data/EmailInsertionSetup.kt
src/main/kotlin/com/criptext/mail/scenes/settings/data/CreateCustomLabelWorker.kt
src/main/res/layout/mailbox_labels_chooser.xml
src/main/res/layout/view_settings_general.xml

Also fixed the position of the version number in the general settings.

Fixed a crashing bug and a validation error for some incoming emails.

---

src/main/kotlin/com/criptext/mail/utils/EventHelper.kt

Also now instead of acknowledging emails in batches, just one big request is done to ack all that need ack.

Fixed a bug that some events were not been acknowledged.

---

.circleci/config.yml
src/main/kotlin/com/criptext/mail/scenes/settings/DevicesListItemListener.kt
src/main/kotlin/com/criptext/mail/scenes/settings/SettingsController.kt
src/main/kotlin/com/criptext/mail/scenes/settings/devices/DeviceAdapter.kt
src/main/kotlin/com/criptext/mail/scenes/settings/devices/DeviceHolder.kt
src/main/kotlin/com/criptext/mail/scenes/settings/labels/LabelWrapperListController.kt
src/main/res/layout/devices_item.xml
src/main/res/values/strings.xml

Also fixed an issue that the label recycler view was not refreshing after loading the labels.

Added a better way to discover the remove device feature.

---

src/main/kotlin/com/criptext/mail/websocket/data/UpdatePeerReadStatusWorker.kt

If the email is not in the data base do not acknowledge the read event for it.

---

build.gradle
src/main/kotlin/com/criptext/mail/db/MailboxLocalDB.kt
src/main/kotlin/com/criptext/mail/scenes/composer/data/SaveEmailWorker.kt

- Email thread count was displaying wrong numbers.
- When you replied an email was been marked as unread.

Fixed a couple of mailbox issues.

---

build.gradle
src/main/kotlin/com/criptext/mail/api/HttpClient.kt
src/main/kotlin/com/criptext/mail/scenes/composer/ComposerController.kt
src/main/kotlin/com/criptext/mail/scenes/composer/ComposerModel.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/FullEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/linking/LinkingScene.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxActivity.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/data/SendMailWorker.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/feed/data/FeedDataSource.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/feed/data/LoadFeedsWorker.kt
src/main/kotlin/com/criptext/mail/scenes/settings/SettingsController.kt
src/main/kotlin/com/criptext/mail/scenes/settings/data/UserSettingsData.kt
src/main/kotlin/com/criptext/mail/scenes/settings/devices/DeviceHolder.kt
src/main/kotlin/com/criptext/mail/scenes/settings/devices/DeviceItem.kt
src/main/kotlin/com/criptext/mail/scenes/signin/SignInSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/signin/holders/ConnectionHolder.kt
src/main/kotlin/com/criptext/mail/utils/UIUtils.kt
src/main/kotlin/com/criptext/mail/utils/ui/ZoomLayout.kt
src/main/res/layout/activity_connection.xml
src/main/res/layout/devices_item.xml
src/main/res/layout/open_full_mail_item.xml
src/main/res/values/strings.xml

- Progress bar animation to avoid having it static on steps that take too much time.
- Made http interceptor only print logs on debug mode.
- Mails can only be sent if all attachments have been uploaded.
- Added last activity for your other devices in settings.
- Email open feeds now says someone if it's yourself , this covers the case for externals when the email you've sent is opened.

Various minor Fixes

---

src/main/kotlin/com/criptext/mail/BaseActivity.kt
src/main/kotlin/com/criptext/mail/androidui/CriptextNotification.kt
src/main/kotlin/com/criptext/mail/api/models/UntrustedDeviceInfo.kt
src/main/kotlin/com/criptext/mail/push/data/IntentExtrasData.kt
src/main/kotlin/com/criptext/mail/scenes/composer/ComposerController.kt
src/main/kotlin/com/criptext/mail/scenes/composer/data/LoadInitialDataWorker.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/EmailDetailSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/linking/LinkingController.kt
src/main/kotlin/com/criptext/mail/scenes/linking/LinkingModel.kt
src/main/kotlin/com/criptext/mail/scenes/linking/LinkingScene.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/params/LinkingParams.kt
src/main/kotlin/com/criptext/mail/scenes/settings/SettingsController.kt
src/main/kotlin/com/criptext/mail/scenes/settings/changepassword/ChangePasswordController.kt
src/main/kotlin/com/criptext/mail/scenes/settings/recovery_email/RecoveryEmailController.kt
src/main/kotlin/com/criptext/mail/scenes/signin/SignInScene.kt
src/main/kotlin/com/criptext/mail/scenes/signin/SignInSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/signin/SignInSceneModel.kt
src/main/kotlin/com/criptext/mail/scenes/signin/data/LinkDataReadyWorker.kt
src/main/kotlin/com/criptext/mail/scenes/signin/data/LinkStatusData.kt
src/main/kotlin/com/criptext/mail/scenes/signin/data/LinkStatusWorker.kt
src/main/kotlin/com/criptext/mail/scenes/signin/data/SignInResult.kt
src/main/kotlin/com/criptext/mail/scenes/signin/holders/ConnectionHolder.kt
src/main/kotlin/com/criptext/mail/scenes/signin/holders/SignInLayoutState.kt
src/main/kotlin/com/criptext/mail/temporalwebsocket/TempWebSocketController.kt
src/main/kotlin/com/criptext/mail/utils/generaldatasource/data/GeneralResult.kt
src/main/kotlin/com/criptext/mail/utils/generaldatasource/workers/LinkAuthAcceptWorker.kt
src/main/kotlin/com/criptext/mail/websocket/WebSocketEventListener.kt

- Aesthetic tweaks to link devices to show the correct device type.
- Changes in the data received in some of the events for link devices.
- Fixed reply all adding you to cc list if you were there in an incoming email.

Added device types for connection holder and some other tweaks.

---

src/main/kotlin/com/criptext/mail/androidui/CriptextNotification.kt
src/main/kotlin/com/criptext/mail/scenes/composer/data/MailBody.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/FullEmailHolder.kt
src/main/kotlin/com/criptext/mail/utils/WebViewUtils.kt
src/main/kotlin/com/criptext/mail/utils/ui/TextDrawable.java
src/main/res/layout/open_full_mail_item.xml

Also push notifications minor improvement

empty email detail fix and criptext quote standard implemented

---

src/main/kotlin/com/criptext/mail/db/dao/ContactDao.kt
src/main/kotlin/com/criptext/mail/db/dao/EmailContactDao.kt
src/main/kotlin/com/criptext/mail/db/dao/EmailDao.kt
src/main/kotlin/com/criptext/mail/db/dao/EmailLabelDao.kt
src/main/kotlin/com/criptext/mail/db/dao/FileDao.kt
src/main/kotlin/com/criptext/mail/db/dao/FileKeyDao.kt
src/main/kotlin/com/criptext/mail/db/dao/LabelDao.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/EmailDetailSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/settings/SettingsLogoutDialog.kt
src/main/kotlin/com/criptext/mail/utils/generaldatasource/data/UserDataWriter.kt

- Also removed timer from logout dialog.
- Also fixed bug with Unsending of Emails.

Added pagination for the creation of the link devices file.

---

src/main/kotlin/com/criptext/mail/BaseActivity.kt
src/main/kotlin/com/criptext/mail/scenes/composer/data/PostEmailBody.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/data/EmailInsertionSetup.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/data/ResendEmailsWorker.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/data/SendMailWorker.kt
src/main/kotlin/com/criptext/mail/scenes/settings/data/GetUserSettingsWorker.kt
src/main/kotlin/com/criptext/mail/scenes/settings/data/UserSettingsData.kt
src/main/kotlin/com/criptext/mail/scenes/settings/devices/DeviceItem.kt
src/main/kotlin/com/criptext/mail/signal/SignalExternalAddress.kt
src/main/res/values/strings.xml

Various minor adjustments for the code and also managed externals and devices order sorting.

---

src/main/kotlin/com/criptext/mail/BaseActivity.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/AttachmentHistoryPopUp.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/EmailContactInfoPopup.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/ReadHistoryPopUp.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/FullEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/PartialEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/feed/ui/FeedItemHolder.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/holders/EmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/settings/devices/DeviceHolder.kt
src/main/kotlin/com/criptext/mail/utils/DateAndTimeUtils.kt
src/main/kotlin/com/criptext/mail/utils/UIUtils.kt
src/main/res/layout/activity_form_signup.xml
src/main/res/layout/activity_password_login.xml
src/main/res/layout/activity_signin_form.xml
src/main/res/layout/attachment_history_item.xml
src/main/res/layout/empty_trash_warning_dialog.xml
src/main/res/layout/mail_item_option_move_to.xml
src/main/res/layout/mailbox_move_to.xml
src/main/res/layout/nav_feed.xml
src/main/res/layout/welcome_tour_dialog.xml
src/main/res/menu/menu_webview.xml
src/main/res/values-es/strings.xml
src/main/res/values/strings.xml

Added support for spanish language.

---

src/main/AndroidManifest.xml
src/main/kotlin/com/criptext/mail/scenes/mailbox/data/EmailThread.kt
src/main/kotlin/com/criptext/mail/scenes/settings/devices/DeviceItem.kt

- You can share from file system more file types.
- Added a new scenario for when ordering devices in the device list.
- Now EmailPreview on Mailbox only show first names.

Fixed some minor issues.

---

build.gradle
src/androidTest/kotlin/com/criptext/mail/scenes/mailbox/data/ResendEmailWorkerTest.kt
src/androidTest/kotlin/com/criptext/mail/scenes/mailbox/data/SendEmailWorkerTest.kt
src/main/kotlin/com/criptext/mail/api/HttpClient.kt
src/main/kotlin/com/criptext/mail/push/PushController.kt
src/main/kotlin/com/criptext/mail/push/data/PushDataSource.kt
src/main/kotlin/com/criptext/mail/push/data/PushRequest.kt
src/main/kotlin/com/criptext/mail/push/data/PushResult.kt
src/main/kotlin/com/criptext/mail/push/workers/GetPushEmailWorker.kt
src/main/kotlin/com/criptext/mail/push/workers/UpdateMailboxWorker.kt
src/main/kotlin/com/criptext/mail/scenes/composer/data/PostEmailBody.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/data/MailboxAPIClient.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/workers/ResendEmailsWorker.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/workers/SendMailWorker.kt
src/main/kotlin/com/criptext/mail/scenes/signin/SignInSceneController.kt
src/main/kotlin/com/criptext/mail/utils/EventLoader.kt
src/main/kotlin/com/criptext/mail/utils/generaldatasource/workers/ResendEmailWorker.kt

Issues resolved on this PR: 
* #418 
* #416 
* #410 
* #413 
* #411

Implemented GetEvent on push noification. Now sending email preview encrypted, also some UI tweaks.

---

build.gradle
src/main/kotlin/com/criptext/mail/BaseActivity.kt
src/main/kotlin/com/criptext/mail/db/EmailDetailLocalDB.kt
src/main/kotlin/com/criptext/mail/db/MailboxLocalDB.kt
src/main/kotlin/com/criptext/mail/db/models/Label.kt
src/main/kotlin/com/criptext/mail/scenes/WebViewActivity.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/EmailDetailSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/workers/UpdateEmailThreadLabelsWorker.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/workers/UpdateEmailThreadsLabelsWorker.kt
src/main/kotlin/com/criptext/mail/scenes/settings/profile/ProfileController.kt
src/main/kotlin/com/criptext/mail/utils/Utility.kt

- Added a validation for possible null uri in webview.
- Added a validation for possible null in mailto links
- Fixed an issue that presented when archiving emails and then adding a label to the archived email.
- Fixed an issue for some email clientas that sent inline images as signature and an attachment at the same time.

Various bug fixes.

---

build.gradle
src/main/kotlin/com/criptext/mail/scenes/mailbox/holders/EmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/settings/profile/ProfileController.kt
src/main/kotlin/com/criptext/mail/scenes/signin/SignInScene.kt
src/main/kotlin/com/criptext/mail/scenes/signin/SignInSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/signin/holders/SignInStartHolder.kt
src/main/res/layout/activity_signin_form.xml

- Fixed a bug for the bold replacement in mailbox.
- Added a back button to the sign in layout for when adding an extra account.
- Added a validation for a possible null on profile picture on the profile layout.

Various minor fixes.

---

build.gradle
src/main/AndroidManifest.xml
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/EmailContactInfoPopup.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxSceneModel.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/ThreadListController.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/ui/EmailThreadAdapter.kt
src/main/kotlin/com/criptext/mail/scenes/settings/profile/ProfileScene.kt
src/main/res/layout/activity_emails_detail.xml
src/main/res/layout/activity_profile.xml
src/main/res/layout/include_mailbox.xml
src/main/res/layout/mail_item.xml
src/main/res/menu/mail_options_read_menu.xml
src/main/res/values-v21/styles.xml
src/main/res/values/attr.xml
src/main/res/values/styles.xml

- More on email detail now shows true time.
- Now we have highlight when selecting a mail on mailbox or on the system menus.
- Fixed the update mailbox on background accounts.
- Now on enterprise accounts the 'Delete Account' option will not show.
- Fixed the loading wheel that stayed when you switched between accounts.

Various fixes

---

build.gradle
src/main/kotlin/com/criptext/mail/BaseActivity.kt
src/main/kotlin/com/criptext/mail/androidui/criptextnotification/NotificationOpenMailbox.kt
src/main/kotlin/com/criptext/mail/push/PushController.kt
src/main/kotlin/com/criptext/mail/push/PushData.kt
src/main/kotlin/com/criptext/mail/scenes/ActivityMessage.kt
src/main/kotlin/com/criptext/mail/scenes/composer/ComposerActivity.kt
src/main/kotlin/com/criptext/mail/scenes/composer/ComposerController.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/FullEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/PartialEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxActivity.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/restorebackup/RestoreBackupActivity.kt
src/main/kotlin/com/criptext/mail/scenes/settings/cloudbackup/CloudBackupActivity.kt
src/main/kotlin/com/criptext/mail/scenes/settings/profile/ProfileActivity.kt
src/main/kotlin/com/criptext/mail/utils/file/ActivityMessageUtils.kt
src/main/kotlin/com/criptext/mail/utils/file/FileUtils.kt
src/main/res/values-es/strings.xml
src/main/res/values/strings.xml
src/test/java/com/criptext/mail/scenes/composer/ComposerContollerUiTest.kt
src/test/java/com/criptext/mail/scenes/composer/ComposerControllerDataSourceEventsTest.kt

Also localized OPEN push notification.

Now sharing to the app works as intended in all considered cases.

---

src/main/kotlin/com/criptext/mail/BaseActivity.kt
src/main/kotlin/com/criptext/mail/scenes/WebViewActivity.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/FullEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/mailbox/MailboxSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/signin/SignInSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/signup/SignUpSceneController.kt
src/main/res/layout/activity_emails_detail.xml

- Fixed zoom on emails webview
- Now links to apps are handled correctly
- Now contact support takes you to JIRA Helpdesk.

Fixed zoom on emails and also loading deep links from emails.

---

src/main/kotlin/com/criptext/mail/scenes/composer/workers/LoadInitialDataWorker.kt
src/main/kotlin/com/criptext/mail/utils/generaldatasource/data/UserDataWriter.kt
src/main/res/layout/activity_aliases.xml
src/main/res/layout/activity_custom_domain.xml

- Fixed Size and margin on progress bar for aliases and custom domain controllers.
- Fixed a bug when trying to fw, when from is not an account or alias belonging to the user.

Final fixes/tweaks for Criptext Plus Release.

---

src/main/kotlin/com/criptext/mail/scenes/composer/ComposerController.kt
src/main/kotlin/com/criptext/mail/scenes/composer/ComposerModel.kt
src/main/kotlin/com/criptext/mail/scenes/composer/Validator.kt

'Save as draft' checks if attachments have been added or removed

---

src/main/kotlin/com/criptext/mail/api/models/PeerContactTrustedChanged.kt
src/main/kotlin/com/criptext/mail/db/EventLocalDB.kt
src/main/kotlin/com/criptext/mail/db/MailboxLocalDB.kt
src/main/kotlin/com/criptext/mail/db/dao/EmailDao.kt
src/main/kotlin/com/criptext/mail/push/data/PushAPIRequestHandler.kt
src/main/kotlin/com/criptext/mail/push/data/PushResult.kt
src/main/kotlin/com/criptext/mail/push/services/HeaderActionService.kt
src/main/kotlin/com/criptext/mail/push/workers/GetPushEmailWorker.kt
src/main/kotlin/com/criptext/mail/push/workers/UpdateMailboxWorker.kt
src/main/kotlin/com/criptext/mail/scenes/composer/ComposerController.kt
src/main/kotlin/com/criptext/mail/scenes/composer/workers/SaveEmailWorker.kt
src/main/kotlin/com/criptext/mail/scenes/webview/WebViewActivity.kt
src/main/kotlin/com/criptext/mail/scenes/webview/WebViewSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/webview/ui/WebViewUIObserver.kt
src/main/kotlin/com/criptext/mail/services/MessagingService.kt
src/main/kotlin/com/criptext/mail/utils/eventhelper/EventHelper.kt
src/main/kotlin/com/criptext/mail/utils/file/CriptextJavaScriptInterface.kt
src/main/res/layout/activity_connection.xml

- Fixed an issue with sending emails with enterprise accounts when it is not the active account.
- Fixed a visual issue on the connection holder.
- Various Fabric crash related fixes.
- Added handler to copy text to clipboard from webview.

Preparation for release.

---

src/main/kotlin/com/criptext/mail/db/models/FullEmail.kt
src/main/kotlin/com/criptext/mail/scenes/composer/ComposerController.kt
src/main/kotlin/com/criptext/mail/scenes/composer/workers/UploadAttachmentWorker.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/EmailDetailScene.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/EmailDetailSceneController.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/FullEmailListAdapter.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/FullEmailRecyclerView.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/FullEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/ParentEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/emaildetail/ui/holders/PartialEmailHolder.kt
src/main/kotlin/com/criptext/mail/scenes/signin/data/SignInSession.kt
src/main/kotlin/com/criptext/mail/scenes/signup/data/StoreAccountTransaction.kt
src/main/kotlin/com/criptext/mail/utils/HTMLUtils.kt
src/main/kotlin/com/criptext/mail/utils/generaldatasource/workers/GetUserSettingsWorker.kt
src/main/res/color/text_color.xml
src/main/res/menu/mail_options_read_menu.xml
src/main/res/menu/mail_options_read_menu_in_spam.xml
src/main/res/menu/mail_options_unread_menu.xml
src/main/res/menu/mail_options_unread_menu_in_spam.xml
src/main/res/values-de/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-ru/strings.xml
src/main/res/values/strings.xml

- Also fixed an issue with the default address and the email not been sent with the selected address.
- Also added a custom report when an upload fails so that we can check each case in a more detailed way.

Added turn on lights for dark emails that have wrong css.
